package com.rnd.app.service;
import com.fasterxml.jackson.databind.ObjectMapper; import com.rnd.app.dto.*; import com.rnd.app.entity.ExportJob; import com.rnd.app.repository.ExportJobRepository; import com.rnd.app.util.*;
import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.*; import java.util.*; import java.util.zip.*;
@Service @RequiredArgsConstructor public class ExportService {
 private static final Set<String> COLS=Set.of("project","plannedStartDate","actualCompletedAt","actualHours","type","status","owner","priority","sprint","module","severity","creator","dueDate","createdAt","updatedAt");
 private static final int MAX_EXPORT_ROWS=10000;
 private final ExportJobRepository jobs; private final WorkItemService workItems; private final ObjectMapper mapper; private final com.rnd.app.repository.ProjectRepository projects;
 @Value("${app.export.path:./data/exports}") private String exportPath;
 @Transactional public ExportJobDto create(Long projectId,Long userId,ExportWorkItemsRequest r){ validate(r); ExportJob job=jobs.save(ExportJob.builder().projectId(projectId).creatorId(userId).status("CREATING").requestJson(write(r)).build());
  try{ var sort=parseSort(r.getSort()); var page=workItems.search(projectId,r.getType(),r.getStatus(),r.getOwnerId(),r.getCreatorId(),r.getSprintId(),r.getPriority(),r.getSeverity(),r.getModule(),r.getTag(),r.getDueFrom(),r.getDueTo(),r.getKeyword(),r.getView(),userId,PageRequest.of(0,MAX_EXPORT_ROWS,sort)); if(page.getTotalElements()>MAX_EXPORT_ROWS)throw new BusinessException(ErrorCode.BAD_REQUEST,"导出结果超过 10000 条，请缩小筛选条件后重试"); Path dir=Paths.get(exportPath).toAbsolutePath().normalize();Files.createDirectories(dir);String name="work-items-"+job.getId()+".xlsx";Path file=dir.resolve(name);writeWorkbook(file,page.getContent(),r.getColumns(),projects.findById(projectId).map(com.rnd.app.entity.Project::getName).orElse(String.valueOf(projectId)));job.setStatus("READY");job.setFileName(name);job.setStoragePath(file.toString());job.setExpiresAt(Instant.now().plus(Duration.ofHours(24)));jobs.save(job);return dto(job);}catch(BusinessException e){throw e;}catch(Exception e){job.setStatus("FAILED");jobs.save(job);throw new BusinessException(ErrorCode.INTERNAL_ERROR,"导出生成失败");}}
 public ExportJob get(Long id,Long userId){return jobs.findByIdAndCreatorId(id,userId).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND));} public ExportJobDto status(Long id,Long uid){return dto(get(id,uid));}
 public Path download(Long id,Long uid){ExportJob j=get(id,uid);if(!"READY".equals(j.getStatus())||j.getExpiresAt()==null||j.getExpiresAt().isBefore(Instant.now()))throw new BusinessException(ErrorCode.NOT_FOUND,"导出文件已过期");Path p=Paths.get(j.getStoragePath());if(!Files.exists(p))throw new BusinessException(ErrorCode.NOT_FOUND);return p;}
 private void validate(ExportWorkItemsRequest r){if(r.getColumns()==null)r.setColumns(List.of("type","status","owner","priority","sprint","dueDate"));if(!COLS.containsAll(r.getColumns())||new HashSet<>(r.getColumns()).size()!=r.getColumns().size())throw new BusinessException(ErrorCode.BAD_REQUEST,"导出列不合法");parseSort(r.getSort());}
 private Sort parseSort(String s){String[]p=s.split(",",-1);if(p.length!=2||!Set.of("createdAt","updatedAt","dueDate","priority","title").contains(p[0])||!Set.of("asc","desc").contains(p[1]))throw new BusinessException(ErrorCode.BAD_REQUEST,"排序不合法");return Sort.by("asc".equals(p[1])?Sort.Direction.ASC:Sort.Direction.DESC,p[0]);}
 private String write(Object o){try{return mapper.writeValueAsString(o);}catch(Exception e){throw new BusinessException(ErrorCode.BAD_REQUEST);}}
 private void writeWorkbook(Path path,List<WorkItemDto> rows,List<String> cols,String projectName)throws IOException{try(var zip=new ZipOutputStream(Files.newOutputStream(path))){entry(zip,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");entry(zip,"_rels/.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");entry(zip,"xl/workbook.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"工作项\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");entry(zip,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");StringBuilder x=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");List<String>head=new ArrayList<>();head.add("ID");head.add("标题");for(String c:cols)head.add(label(c));xmlRow(x,1,head);int n=2;for(var w:rows){List<String>v=new ArrayList<>();v.add(w.getId());v.add(w.getTitle());for(String c:cols)v.add(value(w,c,projectName));xmlRow(x,n++,v);}x.append("</sheetData></worksheet>");entry(zip,"xl/worksheets/sheet1.xml",x.toString());}}
 private void entry(ZipOutputStream z,String name,String text)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(text.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
 private void xmlRow(StringBuilder x,int n,List<String>v){x.append("<row r=\"").append(n).append("\">");for(int i=0;i<v.size();i++)x.append("<c r=\"").append(col(i)).append(n).append("\" t=\"inlineStr\"><is><t>").append(xml(v.get(i))).append("</t></is></c>");x.append("</row>");}
 private String col(int i){StringBuilder s=new StringBuilder();for(i++;i>0;i=(i-1)/26)s.insert(0,(char)('A'+(i-1)%26));return s.toString();} private String xml(String s){return s==null?"":s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 private String label(String c){switch(c){case"project":return"项目";case"plannedStartDate":return"计划开始日期";case"actualCompletedAt":return"实际完成时间";case"actualHours":return"实际工时";case"type":return"类型";case"status":return"状态";case"owner":return"负责人";case"priority":return"优先级";case"sprint":return"迭代";case"module":return"模块";case"severity":return"严重程度";case"creator":return"创建人";case"dueDate":return"到期日";case"createdAt":return"创建时间";default:return"更新时间";}}
 private String value(WorkItemDto x,String c,String projectName){Object v;switch(c){case"project":v=projectName;break;case"plannedStartDate":v=x.getPlannedStartDate();break;case"actualCompletedAt":v=x.getActualCompletedAt();break;case"actualHours":v=x.getActualHours();break;case"type":v=x.getType();break;case"status":v=x.getStatus();break;case"owner":v=x.getOwnerName();break;case"priority":v=x.getPriority();break;case"sprint":v=x.getSprintId();break;case"module":v=x.getModule();break;case"severity":v=x.getSeverity();break;case"creator":v=x.getCreatorName();break;case"dueDate":v=x.getDueDate();break;case"createdAt":v=x.getCreatedAt();break;default:v=x.getUpdatedAt();}return v==null?"":v.toString();}
 private ExportJobDto dto(ExportJob j){return new ExportJobDto(j.getId(),j.getStatus(),j.getFileName(),j.getExpiresAt());}
}
